### ISSUE TITLE
Experimental v0.7

### ISSUE THREAD

**Issue by Deovandski** [Deovandski/Fakktion#15]
#### High Priority
- [x] Broken Devise + Ember-simple-auth #27
- [x] Admin can edit tags.

#### Normal Priority
- [x] Decide on #21, and any further necessary changes to SCSS. Definitely not Bootstrap due to how terrible previous upgrade attempt was...
- [x] Finish up all resources CREATE AND PUT...
- [x] User.create gender to lowercase
- [x] User/create Display Name validation needs to account for a few characters inputted
- [x] User/create Email Regex needs to kick in after 8 characters instead of the current amount
- [x] User/create Password "Too Short" needs to display "8 characters minimum" instead
- [x] User/Create DOB boxes set limit on amount of characters per box for TAB function.
- [x] User/Create DOB display message for dates older than 1900
- [x] Fully cleanup User/create upon Server 200 (and then redirect the user to Login)
- [x] Posts/create change "None" to select a X on the (right/left).
- [x] Posts/Create change Text Dive to a richer text. Implement markup while going at it? Implementing a custom helper instead...
- [x] Post/index revise fixed space for text and allow it to be dynamic with min-height instead.
- [x] Posts/edit | Symbolic link to the above problem
- [x] Index | Change X to "No X Tag selected" in order to reduce guessing about what the upper central panel does.
- [x] Index Topics "Not Found. Check Manage Topics" needs to be more visible... Perhaps setting the bg color to light red to the text itself to red or dark yellow?
- [x] Index |  Add stronger division between Topic and Upper central panel tags,
- [x] Create a Help page #25
- [x] Fix Inner comments 404 issues.
- [x] Comment System. Drop "Cannot by empty" string.
- [x] Maintain at least 10 character needs to remove cursor pointer.
- [x] Comment System Edit is being allowed to anyone... Restrict to owner only.
- [x] Remove Inner comments String from each inner comment rendered.
- [x] "Add Comment" text before render comments.create
- [x] Post/index Title, tex, and each text under Post information need to remove cursor pointer due to possible issues with thinking that it is actually a link, when it is simply a text.
- [x] Post/index Created By User is missing the actual link to the user profile.
- [x] Post/Index links target to _blank 
- [x] Post/index adjusted paddings
- [x] improved helpers to handle undefined Handlebars calls.
- [x] Post/index implemented a better width control solution
- [x] All buttons refactored and specific tag buttons created.
- [x] Application and Index controller refactored to handle tag model.
- [x] Application and Topics.index integration for smooth topic search.
- [x] Refactored how posts were being shown on the index page. Added icons instead of displaying text for #views and #comments 
- [x] Fixed Shared Panel overflow height
- [x] Created helper for # of comments and views of a post.
- [x] Application Loading Page
- [x] About and Support page merge
- [x] Frontend limit on tag sizes.
- [x] Backend limit on tag size.
- [x] Empty tag forms on CREATE with response of 200.
- [x] Navigation of creating resources refactored to be at most 5 navigations away from any other CREATE
- [x] Frontend XSS Mitigation for Resources with Text
- [x] Backend XSS Protection (Like a Boss!)
- [x] Refactored Application Sidebars and central panel to act like toggable modules based on user input. Flex FTW!
- [x] Partials are now under their own folders.
- [x] Posts/create now properly warns about missing tags
- [x] Posts/create Preview mode for Text.
- [x] Flex refactored on current tags selected and HTML.
- [x] More Post date filters so that there is a balance on the # of tags on each side of the screen.
- [x] Refactored Category tag to cover wider topics and Genre tag to be more specific.
- [x] A few resources did not contain css matches or had deprecated ones.
- [x] Tags + Tag page normalization for easier learning curve.
- [x] Blocked non admin users from acessing tag edit routes.
