### ISSUE TITLE
Fakktion Beta Checklist

### ISSUE THREAD

**Issue by Deovandski** [Deovandski/Fakktion#24]
# Beta Ready Checklist
- [x] Create User
- [x] Edit User
- [x] Create Topic
- [x] Edit Topic
- [x] Create Fact Type
- [x] Edit Fact Type
- [x] Create Category
- [x] Edit Category 
- [x] Create Post
- [x] Edit Post
- [x] Create Comment
- [x] Edit Comment
- [x] Create Inner Comment
- [x] Edit Inner Comment

### Other Items left to do.

- [x] Finish up #25
- [x] Redesign Sidebars 
- [x] Alert messages checklist
- [x] Change seeds.rb to the new aggreement
- [x] Refactor Post.index to the new agreement
- [x] Reduce posting limit of all resources to 1 character.
- [x] Finish #10
- [x] Upgrade to v0.10 [AMS Releases](https://github.com/rails-api/active_model_serializers/releases)
- [x] Finish Ubuntu Server 16 Deployment guide
- [x] Finish Ubuntu Server 16 Maintenance guide
- [x] Refactor Topic search (Deprecated on this [commit](https://github.com/Deovandski/Fakktion/commit/46e3aa2808d8b3c0a0dec91e6dce73547552e07a))
