### ISSUE TITLE
Fakktion Alpha Checklist

### ISSUE THREAD

**Issue by Deovandski** [Deovandski/Fakktion#31]
### Tests procedures
- [x] Base tests from all Checklists.

### User.create

Force the following to be default when creating a User:
- [x] admin_messages_count
- [x] comments_count
- [x] facebook_url
- [x] is_admin
- [x] is_super_user
- [x] is_legend
- [x] twitter_utl
- [x] Is the unique keys being checked against?

### User.edit

- [x] is authorization check being used?
- [x] is the Super User check being run for profile check?
- [x] is the Admin check being run for profile check?
- [x] is the Legend check being run for profile check?
- [x] Is the unique keys being checked against?

### User.delete

- [x] Do not allow deletion

### Super User Method Check

- [x] Is the reputation being checked against for super user? (500 Reputation)
- [x] is the user being upgrade/downgrade according to his/her reputation?
- [x] Correct return?

### Admin Method Check

- [x] Is the reputation being checked against for admin? (1500 Reputation)
- [x] is the user being upgrade/downgrade according to his/her reputation?
- [x] Correct return?

### Legend Method Check

- [x] Is the reputation being checked against for legend? (3000 Reputation)
- [x] is the user being upgrade/downgrade according to his/her reputation?
- [x] Correct return?

### Authorization Check

is the following being checked against?
- [x] User authentication token
- [x] email
- [x] user Id
- [x] Is the return of the check correct?

### Genre.create
- [x] Is the counters being set to 0?
- [x] Is the unique name key being checked against?

### Genre.edit
- [x] Is the unique name key being checked against?
- [x] Is the admin check being run?

### FactType.create
- [x] Is the counters being set to 0?
- [x] Is the unique name key being checked against?

### FactType.edit
- [x] Is the unique name key being checked against?
- [x] Is the admin check being run?

### Topic.create
- [x] Is the counters being set to 0?
- [x] Is the unique name key being checked against?

### Topic.edit
- [x] Is the unique name key being checked against?
- [x] Is the admin check being run?

### Category.create
- [x] Is the counters being set to 0?
- [x] Is the unique name key being checked against?

### Category.edit
- [x] Is the unique name key being checked against?
- [x] Is the admin check being run?

### Post.create
- [x] Is there a Topic, Category, FactType and Genre tag present?
- [x] Is the User belongs to present?
- [x] Is the text size limits being followed? min 10/max 1k
- [x] Is the fact and Fiction link REGEX being followed?
- [x] is XSS attacks being prevented like a boss?

### Post.edit
- [x] Is there a Topic, Category, FactType and Genre tag present?
- [x] Is the User belongs to present?
- [x] Is the text size limits being followed? min 10/max 1k
- [x] Is the fact and Fiction link REGEX being followed?
- [x] is XSS attacks being prevented like a boss?
- [x] is the Owner check being performed?

### Comment.create
- [x] Is the User and Post belongs to present?
- [x] Is the text size limits being followed? min 10/max 500
- [x] is XSS attacks being prevented like a boss?

### Comment.edit
- [x] Is the User and Post belongs to present?
- [x] Is the text size limits being followed? min 10/max 500
- [x] is XSS attacks being prevented like a boss?
- [x] is the Owner check being performed?

### InnerComment.create
- [x] Is the User and Comment belongs to present?
- [x] Is the text size limits being followed? min 10/max 250

### InnerComment.edit
- [x] Is the User and Comment belongs to present?
- [x] Is the text size limits being followed? min 10/max 250
- [x] is the owner check being performed?

### InnerComment.delete
- [x] Is there any dependencies?
- [x] is the Owner check/ Legend check being performed?
- [x] Is the associated votes being deleted?

### CommentVote.create
- [x] is the Super User check being run for profile check?
- [x] is the Admin check being run for profile check?
- [x] is the Legend check being run for profile check?
- [x] Is superUser getting 2x the score?
- [x] Is admins getting 3x the score?
- [x] Is legends getting 4x the score?

### CommentVote.edit
- [x] is the Super User check being run for profile check?
- [x] is the Admin check being run for profile check?
- [x] is the Legend check being run for profile check?
- [x] Is superUser getting 2x the score?
- [x] Is admins getting 3x the score?
- [x] Is legends getting 4x the score?

### InnerCommentVote.create
- [x] is the Super User check being run for profile check?
- [x] is the Admin check being run for profile check?
- [x] is the Legend check being run for profile check?
- [x] Is superUser getting 2x the score?
- [x] Is admins getting 3x the score?
- [x] Is legends getting 4x the score?

### InnerCommentVote.edit
- [x] is the Super User check being run for profile check?
- [x] is the Admin check being run for profile check?
- [x] is the Legend check being run for profile check?
- [x] Is superUser getting 2x the score?
- [x] Is admins getting 3x the score?
- [x] Is legends getting 4x the score?

### Token Validation
- [x] is the check being performed upon LocalStorage usage?
- [x] is the appropriate actions being taken upon 403?

### User Signup
- [x] Is all the required fields correctly being filled?
- [x] is all warning for required fields implemented?
- [x] is all resources being sent upon store.save()?

### User.edit
- [x] is owner check authorization being checked upon entering route?
- [x] Is the unique keys being checked against?
- [x] Resources being reloaded upon edit canceled?
- [x] Is the resources being sent?
- [x] edit.js 288: this.get(...).rollbackAttributes is not a function

### AdminMessage.create
- [x] Is is fully disabled?

### AdminMessage.edit
- [x] Is is fully disabled?

### Genre.create
- [x] Is the counters being set to 0?
- [x] Is the unique name key being checked against?
- [x] Is the resources being sent?

### Genre.edit
- [x] Is the unique name key being checked against?
- [x] Is the admin check being run?
- [x] Resources being reloaded upon edit canceled?
- [x] Is the resources being sent?

### FactType.create
- [x] Is the counters being set to 0?
- [x] Is the unique name key being checked against?
- [x] Is the resources being sent?

### FactType.edit
- [x] Is the unique name key being checked against?
- [x] Is the admin check being run?
- [x] Resources being reloaded upon edit canceled?
- [x] Is the resources being sent?

### Topic.create
- [x] Is the counters being set to 0?
- [x] Is the unique name key being checked against?
- [x] Is the resources being sent?

### Topic.edit
- [x] Is the unique name key being checked against?
- [x] Is the admin check being run?
- [x] Resources being reloaded upon edit canceled?
- [x] Is the resources being sent?

### Category.create
- [x] Is the counters being set to 0?
- [x] Is the unique name key being checked against?
- [x] Is the resources being sent?

### Category.edit
- [x] Is the unique name key being checked against?
- [x] Is the admin check being run?
- [x] Resources being reloaded upon edit canceled?
- [x] Is the resources being sent?

### Post.create
- [x] Is there a Topic, Category, FactType and Genre tag present?
- [x] Is the User belongs to present?
- [x] Is the text size limits being followed? min 10/max 2k
- [x] Is the resources being sent?

### Post.edit
- [x] Is there a Topic, Category, FactType and Genre tag present?
- [x] Is the text size limits being followed? min 10/max 2k
- [x] Is the fact and Fiction link REGEX being followed?
- [x] is the Owner check being performed?
- [x] Resources being reloaded upon edit canceled?
- [x] Is the resources being sent?

### Comment.create
- [x] Is the User and Post belongs to present?
- [x] Is the text size limits being followed? min 10/max 1k
- [x] Is the resources being sent?

### Comment.edit
- [x] Is the User and Post belongs to present?
- [x] Is the text size limits being followed? min 10/max 1k
- [x] Is the resources being sent?
- [x] is the Owner check being performed?
- [x] Resources being reloaded upon edit canceled?

### InnerComment.create
- [x] Is the User and Comment belongs to present?
- [x] Is the text size limits being followed? min 10/max 500
- [x] Is the resources being sent?

### InnerComment.edit
- [x] Is the User and Comment belongs to present?
- [x] Is the text size limits being followed? min 10/max 500
- [x] is the owner check being performed?
- [x] Resources being reloaded upon edit canceled?
- [x] Is the resources being sent?

### CommentVote.create
- [x] is the Super User check being run for profile check?
- [x] is the Admin check being run for profile check?
- [x] is the Legend check being run for profile check?
- [x] Is superUser getting 2x the score?
- [x] Is admins getting 3x the score?
- [x] Is legends getting 4x the score?
- [x] Is the resources being sent?

### CommentVote.edit
- [x] is the Super User check being run for profile check?
- [x] is the Admin check being run for profile check?
- [x] is the Legend check being run for profile check?
- [x] Is superUser getting 2x the score?
- [x] Is admins getting 3x the score?
- [x] Is legends getting 4x the score?
- [x] Is the resources being sent?

### InnerCommentVote.create
- [x] is the Super User check being run for profile check?
- [x] is the Admin check being run for profile check?
- [x] is the Legend check being run for profile check?
- [x] Is superUser getting 2x the score?
- [x] Is admins getting 3x the score?
- [x] Is legends getting 4x the score?

### InnerCommentVote.edit
- [x] is the Super User check being run for profile check?
- [x] is the Admin check being run for profile check?
- [x] is the Legend check being run for profile check?
- [x] Is superUser getting 2x the score?
- [x] Is admins getting 3x the score?
- [x] Is legends getting 4x the score?

### Other Frontend checks
- [x] Perform Validation on this.route('header');
- [x] Perform Validation on this.route('login', { path: '/login' });
- [x] Perform Validation on this.route('adminPanel', { path: '/adminPanel' });
- [x] Perform Validation on 
```
this.route('users', function(){
    this.route('create');
  });
```
- [x] Perform Validation on 
```
this.route('user', { path:'user/:user_id' }, function() {
    this.route('edit');
    this.route('posts'); // view all posts by x User
    this.route('comments'); // View all Comments by x User
  });
```
- [x] Perform Validation on 
```
this.route('adminMessages', function(){
    this.route('create');
  });
```
- [x] Perform Validation on 
```
this.route('adminMessage', { path:'adminMessage/:admin_message_id' }, function() {
    this.route('edit');
  });
```

- [x] Perform Validation on 
```
 this.route('posts', function(){
    this.route('create');
  });
```

- [x] Perform Validation on 
```
this.route('post', { path:'post/:post_id' }, function() {
    this.route('edit');
    this.route('comments', function(){
      this.route('create');
    });
```
- [x] Perform Validation on 
```
this.route('comment', { path:'comment/:comment_id' }, function() {
      this.route('innerComments', function(){
        this.route('create');
      });
      this.route('innerComment', { path:'innerComment/:inner_comment_id' }, function() {
      });
    });
  });
```

- [x] Perform Validation on 
```
  this.route('genres', function(){
    this.route('create');
  });
  this.route('genre', { path:'genre/:genre_id' }, function() {
    this.route('edit');
  });
```
  
- [x] Perform Validation on 
```
  this.route('factTypes', function(){
    this.route('create');
  });
  this.route('factType', { path:'factType/:factType_id' }, function() {
    this.route('edit');
  });
```
  
- [x] Perform Validation on 
```
  this.route('topics', function(){
    this.route('create');
  });
  this.route('topic', { path:'topic/:topic_id' }, function() {
    this.route('edit');
  });
```
  
- [x] Perform Validation on 
```
  this.route('categories', function(){
    this.route('create');
  });
  this.route('category', { path:'category/:category_id' }, function() {
    this.route('edit');
 });
```

- [x] Perform Validation on this.route('footer');
- [x] Perform Validation on this.route('legalInfo');
- [x] Perform Validation on this.route('privacyInfo');
- [x] Perform Validation on this.route('support');
- [x] Perform Validation on this.route('not-found', { path: '/*wildcard' });

### Hacking Attempts
- [x] Is LocalStorage not being fooled by tampering with its data?
- [x] Is Backend reinforcing tokens?
- [x] Are Passwords secured?
- [x] Is reputation out of reach from being manipulated through update(params)?

### Other Checks
- [x] All code follow spaces instead of tabs.
- [x] All Header buttons works
- [x] All Footer buttons works
- [x] All Post related buttons works
- [x] All commenting system buttons works
- [x] All Tags buttons works
- [x] Frontend Coverage is above 75%?
- [x] Backend Coverage is above 90%?

**Comment by Deovandski** [comment]
## Frontend Checks

### Token Validation
- [ ] is the check being performed upon LocalStorage usage?
- [ ] is the appropriate actions being taken upon 403?

### User Signup
- [ ] Is all the required fields correctly being filled?
- [ ] is all warning for required fields implemented?
- [ ] is all resources being sent upon store.save()?

### User.edit
- [ ] is owner check authorization being checked upon entering route?
- [ ] Is the unique keys being checked against?
- [ ] Resources being reloaded upon edit canceled?
- [ ] Is the resources being sent?

### User.delete
- [ ] Allow deletion only if there are no dependencies.

### AdminMessage.create
- [ ] Only allow route entrance if admin.

### AdminMessage.edit
- [ ] Only allow route entrance if admin.
- [ ] Is the return of the check correct?
- [ ] Do not allow edit of messages older than 1 month to prevent issues with AdminOldMessagesCheck.
- [ ] Resources being reloaded upon edit canceled?
- [ ] Is the resources being sent?

### AdminMessage.delete
- [ ] Only allow route entrance if admin.
- [ ] Only allow deletion if older than 15 days.
- [ ] Only Legend can delete messages manually.

### Genre.create
- [ ] Is the counters being set to 0?
- [ ] Is the unique name key being checked against?
- [ ] Is the resources being sent?

### Genre.edit
- [ ] Is the unique name key being checked against?
- [ ] Is the admin check being run?
- [ ] Resources being reloaded upon edit canceled?
- [ ] Is the resources being sent?

### Genre.delete
- [ ] is dependencies check being run?
- [ ] Is the legend check being run?

### FactType.create
- [ ] Is the counters being set to 0?
- [ ] Is the unique name key being checked against?
- [ ] Is the resources being sent?

### FactType.edit
- [ ] Is the unique name key being checked against?
- [ ] Is the admin check being run?
- [ ] Resources being reloaded upon edit canceled?
- [ ] Is the resources being sent?

### FactType.delete
- [ ] is dependencies check being run?
- [ ] Is the legend check being run?

### Topic.create
- [ ] Is the counters being set to 0?
- [ ] Is the unique name key being checked against?
- [ ] Is the resources being sent?

### Topic.edit
- [ ] Is the unique name key being checked against?
- [ ] Is the admin check being run?
- [ ] Resources being reloaded upon edit canceled?
- [ ] Is the resources being sent?

### Topic.delete
- [ ] is dependencies check being run?
- [ ] Is the legend check being run?

### Category.create
- [ ] Is the counters being set to 0?
- [ ] Is the unique name key being checked against?
- [ ] Is the resources being sent?

### Category.edit
- [ ] Is the unique name key being checked against?
- [ ] Is the admin check being run?
- [ ] Resources being reloaded upon edit canceled?
- [ ] Is the resources being sent?

### Category.delete
- [ ] is dependencies check being run?
- [ ] Is the delete check being run?

### Post.create
- [ ] Is there a Topic, Category, FactType and Genre tag present?
- [ ] Is the User belongs to present?
- [ ] Is the text size limits being followed? min 10/max 1k
- [ ] Is the resources being sent?

### Post.edit
- [ ] Is there a Topic, Category, FactType and Genre tag present?
- [ ] Is the text size limits being followed? min 10/max 1k
- [ ] Is the fact and Fiction link REGEX being followed?
- [ ] is the Owner check being performed?
- [ ] Resources being reloaded upon edit canceled?
- [ ] Is the resources being sent?

### Post.delete
- [ ] Is there any dependencies?
- [ ] is the Owner check/ Admin check being performed?

### Comment.create
- [ ] Is the User and Post belongs to present?
- [ ] Is the text size limits being followed? min 10/max 500
- [ ] Is the resources being sent?

### Comment.edit
- [ ] Is the User and Post belongs to present?
- [ ] Is the text size limits being followed? min 10/max 500
- [ ] Is the resources being sent?
- [ ] is the Owner check being performed?
- [ ] Resources being reloaded upon edit canceled?

### Comment.delete
- [ ] Is there any dependencies?
- [ ] is the Owner check/ Legend check being performed?
- [ ] Is the associated votes being deleted?

### InnerComment.create
- [ ] Is the User and Comment belongs to present?
- [ ] Is the text size limits being followed? min 10/max 250
- [ ] Is the resources being sent?

### InnerComment.edit
- [ ] Is the User and Comment belongs to present?
- [ ] Is the text size limits being followed? min 10/max 250
- [ ] is the owner check being performed?
- [ ] Resources being reloaded upon edit canceled?
- [ ] Is the resources being sent?

### InnerComment.delete
- [ ] Is there any dependencies?
- [ ] is the Owner check/ Legend check being performed?
- [ ] Is the associated votes being deleted?

### CommentVote.create
- [ ] is the Super User check being run for profile check?
- [ ] is the Admin check being run for profile check?
- [ ] is the Legend check being run for profile check?
- [ ] Is superUser getting 2x the score?
- [ ] Is admins getting 3x the score?
- [ ] Is legends getting 4x the score?
- [ ] Is the resources being sent?

### CommentVote.edit
- [ ] is the Super User check being run for profile check?
- [ ] is the Admin check being run for profile check?
- [ ] is the Legend check being run for profile check?
- [ ] Is superUser getting 2x the score?
- [ ] Is admins getting 3x the score?
- [ ] Is legends getting 4x the score?
- [ ] Is the resources being sent?

### CommentVote.delete
- [ ] Do not allow direct deletion.

### InnerCommentVote.create
- [ ] is the Super User check being run for profile check?
- [ ] is the Admin check being run for profile check?
- [ ] is the Legend check being run for profile check?
- [ ] Is superUser getting 2x the score?
- [ ] Is admins getting 3x the score?
- [ ] Is legends getting 4x the score?

### InnerCommentVote.edit
- [ ] is the Super User check being run for profile check?
- [ ] is the Admin check being run for profile check?
- [ ] is the Legend check being run for profile check?
- [ ] Is superUser getting 2x the score?
- [ ] Is admins getting 3x the score?
- [ ] Is legends getting 4x the score?

### InnerCommentVote.delete
- [ ] Do not allow direct deletion.
